"""Developer tool: regenerate ``schema_data.py`` from the engine sources of this repository.

The converter does not need the engine sources at run time. This script reads the ``FieldParse`` tables
(``{ "Field", parseFunction, userData, offset }``) and the module factory registrations, and writes

* ``FIELD_PARSERS``: field name -> sorted list of the parse functions used for that name anywhere in the engine,
* ``MODULE_NAMES``: every module name the module factories register,
* ``TOP_LEVEL_BLOCKS``: the block types ``INI.cpp`` knows (the ``theTypeTable``).

Usage (from the repository root)::

    python3 tools/zharmy/gen_schema.py            # rewrites tools/zharmy/schema_data.py
"""

import os
import re
import sys

ROOTS = ("GeneralsMD", "Core")
ENTRY = re.compile(r'\{\s*"([A-Za-z0-9_]+)"\s*,\s*([A-Za-z_:0-9<>]+)\s*,')
ADD_MODULE = re.compile(r'\baddModule\(\s*(\w+)\s*\)')
TYPE_ENTRY = re.compile(r'\{\s*"(\w+)"\s*,\s*([\w:]+)\s*\}')


INIT_CALL = re.compile(r"initFromINI\w*\s*\(")
HEADER = re.compile(r"^[A-Za-z_][^\n;{}]*?\b([A-Za-z_]\w*(?:::\w+)*)\s*\(([^\n]*)", re.M)


def nested_functions(text):
    """Short names of functions that call ``initFromINI`` while parsing a field: such a field opens a block that
    has its own ``End`` (``ArmorSet``, ``SideInfo``, the FX nuggets ...)."""
    out = set()
    for m in INIT_CALL.finditer(text):
        start = text.rfind("\n}", 0, m.start())
        seg = text[start + 1:m.start()] if start >= 0 else text[:m.start()]
        hdr = [h for h in HEADER.findall(seg) if "INI" in h[1]]
        if hdr:
            out.add(hdr[-1][0].split("::")[-1])
    return out


def repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", ".."))


def scan(root):
    fields = {}
    modules = set()
    nested = set()
    for top in ROOTS:
        for dirpath, _dirs, files in os.walk(os.path.join(root, top)):
            for name in files:
                if not name.endswith((".cpp", ".h", ".inl")):
                    continue
                path = os.path.join(dirpath, name)
                try:
                    with open(path, encoding="latin-1") as handle:
                        text = handle.read()
                except OSError:
                    continue
                nested |= nested_functions(text)
                for m in ENTRY.finditer(text):
                    fn = m.group(2)
                    if fn in ("nullptr", "NULL"):
                        continue
                    fields.setdefault(m.group(1), set()).add(fn)
                if name in ("ModuleFactory.cpp", "W3DModuleFactory.cpp"):
                    modules.update(ADD_MODULE.findall(text))
    return fields, modules, nested


def top_level_blocks(root):
    path = os.path.join(root, "Core", "GameEngine", "Source", "Common", "INI", "INI.cpp")
    with open(path, encoding="latin-1") as handle:
        text = handle.read()
    start = text.index("theTypeTable[]")
    end = text.index("};", start)
    return sorted(m.group(1) for m in TYPE_ENTRY.finditer(text[start:end]))


def main():
    root = repo_root()
    fields, modules, nested = scan(root)
    blocks = top_level_blocks(root)
    out = ['"""Generated by gen_schema.py from the engine sources. Do not edit by hand."""', ""]
    out.append("TOP_LEVEL_BLOCKS = %r" % (tuple(blocks),))
    out.append("")
    out.append("MODULE_NAMES = frozenset(%r)" % (sorted(modules),))
    out.append("")
    nested_fields = sorted(f for f, fns in fields.items()
                           if any(fn.split("::")[-1] in nested for fn in fns))
    out.append("# fields whose value is a block with its own End (their parse function calls initFromINI)")
    out.append("NESTED_FIELDS = frozenset(%r)" % (nested_fields,))
    out.append("")
    out.append("FIELD_PARSERS = {")
    for name in sorted(fields):
        out.append("    %r: %r," % (name, tuple(sorted(fields[name]))))
    out.append("}")
    out.append("")
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "schema_data.py")
    with open(target, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    print("wrote %s: %d field names, %d modules, %d block types" % (target, len(fields), len(modules), len(blocks)))


if __name__ == "__main__":
    sys.exit(main())
