"""Game text tables: the ``.str`` text format and the compiled ``.csf`` format.

Both layouts come from ``GameTextManager`` (Core/GameEngine/Source/GameClient/GameText.cpp).

STR (``Data\\Generals.str``, tried first in release builds)::

    // comment
    LABEL:Name
    "text with \\n escapes"
    END

CSF (``Data\\<Language>\\Generals.csf``)::

    header   " FSC" version labels strings skip language   (six little endian int32)
    label    " LBL" numStrings labelLength label-bytes
    string   " RTS" length UTF-16LE-text-bitwise-complemented
             (" RTSW" additionally carries the speech file name)
"""

import re
import struct


def escape_text(text):
    """Escape a Python string for the STR format."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            if ord(ch) > 255:
                raise ValueError("STR text must be Latin-1: %r" % text)
            out.append(ch)
    return "".join(out)


class StringTable:
    """An ordered collection of (label -> text) entries."""

    LABEL_RE = re.compile(r"^[A-Za-z0-9_:.\- ]+$")

    def __init__(self):
        self.entries = {}

    def add(self, label, text, speech=""):
        if label.lower() in {k.lower() for k in self.entries}:
            raise ValueError("duplicate string label %r" % label)
        if not self.LABEL_RE.match(label):
            raise ValueError("bad label %r" % label)
        self.entries[label] = (text, speech)

    def labels(self):
        return list(self.entries)

    def to_str(self):
        lines = ["// Generated by the StarterPack build. Original text, GPL-3.0-or-later.", ""]
        for label in sorted(self.entries, key=str.lower):
            text, speech = self.entries[label]
            lines.append(label)
            lines.append('"%s"%s' % (escape_text(text), (" " + speech) if speech else ""))
            lines.append("END")
            lines.append("")
        return "\n".join(lines).encode("latin-1")

    def to_csf(self, language_id=0):
        out = bytearray()
        out += b" FSC"
        out += struct.pack("<iiiii", 3, len(self.entries), len(self.entries), 0, language_id)
        for label in sorted(self.entries, key=str.lower):
            text, speech = self.entries[label]
            out += b" LBL" + struct.pack("<ii", 1, len(label)) + label.encode("ascii")
            units = text.encode("utf-16-le")
            comp = bytes(b ^ 0xFF for b in units)
            if speech:
                out += b"WRTS"
                out += struct.pack("<i", len(units) // 2) + comp
                out += struct.pack("<i", len(speech)) + speech.encode("ascii")
            else:
                out += b" RTS" + struct.pack("<i", len(units) // 2) + comp
        return bytes(out)


def parse_str(data):
    """Parse STR bytes like ``GameTextManager::parseStringFile``. Returns {label: text}."""
    text = data.decode("latin-1").replace("\r\n", "\n")
    lines = text.split("\n")
    result = {}
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("//"):
            continue
        label = line
        value = None
        while i < len(lines):
            line = lines[i].strip()
            i += 1
            if line.upper() == "END":
                break
            if line.startswith('"'):
                # Read to the closing, un-escaped quote.
                body = []
                slash = False
                buf = line[1:]
                while True:
                    done = False
                    for ch in buf:
                        if ch == "\\" and not slash:
                            slash = True
                            body.append(ch)
                            continue
                        if ch == '"' and not slash:
                            done = True
                            break
                        slash = False
                        body.append(ch)
                    if done:
                        break
                    body.append(" ")
                    buf = lines[i]
                    i += 1
                value = _unescape("".join(body))
        if value is None:
            raise ValueError("label %r has no string" % label)
        if label in result:
            raise ValueError("duplicate label %r" % label)
        result[label] = value
    return result


def _unescape(raw):
    out = []
    slash = False
    for ch in raw:
        if slash:
            slash = False
            out.append({"n": "\n", "t": "\t"}.get(ch, ch))
        elif ch == "\\":
            slash = True
        else:
            out.append(ch)
    return "".join(out)


def parse_csf(data):
    """Parse CSF bytes like ``GameTextManager::parseCSF``. Returns {label: text}."""
    if data[:4] != b" FSC":
        raise ValueError("not a CSF file")
    pos = 24
    result = {}
    while pos < len(data):
        if data[pos:pos + 4] != b" LBL":
            raise ValueError("expected label at %d" % pos)
        num_strings, length = struct.unpack_from("<ii", data, pos + 4)
        pos += 12
        label = data[pos:pos + length].decode("ascii")
        pos += length
        first = None
        for n in range(num_strings):
            tag = data[pos:pos + 4]
            (length,) = struct.unpack_from("<i", data, pos + 4)
            pos += 8
            comp = data[pos:pos + length * 2]
            pos += length * 2
            if n == 0:
                first = bytes(b ^ 0xFF for b in comp).decode("utf-16-le")
            if tag == b"WRTS":
                (slen,) = struct.unpack_from("<i", data, pos)
                pos += 4 + slen
        result[label] = first
    return result
